name: quality-intelligence
channels:
  - conda-forge
dependencies:
  - python=3.11
  - openai>=1.0.0
  - loguru>=0.7.2
  - psycopg>=3.1.18
  - python-dotenv>=1.0.1
  - pypdf>=4.2.0
  - cryptography>=3.1
  - poppler
  - streamlit>=1.36.0
  - pip
